import "./globals.css";
import {Inter} from 'next/font/google'
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";


const inter = Inter({
  subsets:['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-inter'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
       <data className="bg-grid"></data>
       <Navigation/>
       <main className="container page">{children}</main>
       <Footer/>
      </body>
    </html>
  );
}
